version: '3'

services:
    php:
        build:
            target: php-fpm-dev
            dockerfile: docker/Dockerfile
            context: ./
        container_name: php-fpm
        volumes:
          - ./:/srv/app

    nginx:
        build:
            target: nginx-dev
            dockerfile: docker/Dockerfile
            context: ./
        container_name: nginx
        volumes:
          - ./:/srv/app
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - 8080:80